services:
  teralux-backend:
    image: ghcr.io/pt-perkasa-pilar-utama/teralux-backend:latest
    container_name: teralux-backend
    ports:
      - "8081:8080"
    env_file:
      - .env
    environment:
      - DB_TYPE=sqlite
      - DB_SQLITE_PATH=/app/tmp/teralux.db
    volumes:
      - teralux_data:/app/tmp
    restart: unless-stopped

volumes:
  teralux_data: